# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops
trigger:
  - master

strategy:
  matrix:
    # linux:
    #   imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    # windows:
    #   imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- bash: |
    npm run rebuild
    npm run release
#    npm test

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/TEST-RESULTS.xml'
#     testRunTitle: 'Test results for JavaScript'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- bash: |
    mkdir release
    cp $(System.DefaultWorkingDirectory)/dist/*.exe $(System.DefaultWorkingDirectory)/release
    cp $(System.DefaultWorkingDirectory)/dist/*.snap $(System.DefaultWorkingDirectory)/release
    cp $(System.DefaultWorkingDirectory)/dist/*.AppImage $(System.DefaultWorkingDirectory)/release
    cp $(System.DefaultWorkingDirectory)/dist/*.dmg $(System.DefaultWorkingDirectory)/release
    cp $(System.DefaultWorkingDirectory)/dist/*.dmg.blockmap $(System.DefaultWorkingDirectory)/release

- task: PublishBuildArtifacts@1
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/release'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
