# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops
trigger:
  - production

strategy:
  matrix:
    # linux:
    #   imageName: 'ubuntu-latest'
    # mac:
    #   imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

variables:
  - group: electron-builder-github

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- bash: './release-publish.sh'
  displayName: 'Build release and publish to GitHub'
  env:
    GH_TOKEN: $(GitHubToken)
#    DEBUG: electron-builder

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- task: CopyFiles@2
  displayName: 'Copy Windows NSIS files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
      dist/*.msi
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: CopyFiles@2
#   displayName: 'Copy Windows zip files to: $(Build.ArtifactStagingDirectory)'
#   inputs:
#     Contents: |
#       dist/*.zip
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts to Azure'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'release'
